
services:
    mysql:
        container_name: wordpress_db
        environment:
            - MYSQL_ROOT_PASSWORD=pass
            - MYSQL_DATABASE=wordpressdb
            - MYSQL_USER=wordpress
            - MYSQL_PASSWORD=wordpress
        volumes:
            - db_data:/var/lib/mysql
        image: mysql:latest
    app:
        container_name: wordpress_app
        environment:
            - WORDPRESS_DB_HOST=wordpress_db
            - WORDPRESS_DB_USER=wordpress
            - WORDPRESS_DB_PASSWORD=wordpress
            - WORDPRESS_DB_NAME=wordpressdb
        ports:
            - 80:80
        volumes:
            - wp_data:/var/www/html
        image: wordpress
volumes:
    db_data:
    wp_data:
        