services:
    taskboard_app:
        container_name: taskboard_app
        networks:
            - taskboard_network
        ports:
            - 5000:80
        image: isolenkoff/taskboard_app
    server:
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=MSSQL*Pass01
        ports:
            - 1433:1433
        volumes:
            - sql_data:/var/opt/mssql
        container_name: mssql_server
        networks:
            - taskboard_network
        image: mcr.microsoft.com/mssql/server
networks:
    taskboard_network:
volumes:
    sql_data:
      external: true